tasks:
  - init: |
      cd /workspace
      wget https://github.com/sass/dart-sass/releases/download/1.56.1/dart-sass-1.56.1-linux-x64.tar.gz
      tar -xf dart-sass-1.56.1-linux-x64.tar.gz      
  - command: |
      /workspace/statyk/build.sh
      export PATH=$PATH:/workspace/statyk/output
      mkdir test-project
      cd test-project
      statyk init
      cd ..
      mv /workspace/dart-sass/sass /workspace/statyk/output
      


